FROM infiniflow/ragflow-base:v2.0
USER  root

WORKDIR /ragflow

## for cuda > 12.0
RUN pip uninstall -y onnxruntime-gpu
ADD ./wheels/onnxruntime_gpu-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl ./onnxruntime_gpu-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
RUN pip install onnxruntime_gpu-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
RUN rm ./onnxruntime_gpu-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl

RUN pip install -U openai --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip install fire --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip install neo4j --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple 


ADD ./web ./web
# RUN cd ./web && npm i --force && npm run build

ADD ./api ./api
ADD ./conf ./conf
ADD ./deepdoc ./deepdoc
ADD ./rag ./rag
ADD ./agent ./agent
ADD ./graphrag ./graphrag

ENV PYTHONPATH=/ragflow/
ENV HF_ENDPOINT=https://hf-mirror.com

ADD docker/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
